[2023-07-22T23:41:50.064+0000] {processor.py:157} INFO - Started process (PID=98837) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:41:50.065+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:41:50.066+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:41:50.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:41:50.085+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:41:50.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:41:50.086+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:41:50.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.054 seconds
[2023-07-22T23:42:20.832+0000] {processor.py:157} INFO - Started process (PID=98899) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:20.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:42:20.834+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:42:20.834+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:20.840+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:42:20.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:42:20.842+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:20.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.037 seconds
[2023-07-22T23:42:51.603+0000] {processor.py:157} INFO - Started process (PID=98962) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:51.604+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:42:51.606+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:42:51.605+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:51.613+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:42:51.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:42:51.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:42:51.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.064 seconds
[2023-07-22T23:43:22.325+0000] {processor.py:157} INFO - Started process (PID=99026) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:22.327+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:43:22.328+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:43:22.328+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:22.334+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:43:22.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:43:22.335+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:22.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.034 seconds
[2023-07-22T23:43:52.485+0000] {processor.py:157} INFO - Started process (PID=99090) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:52.486+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:43:52.487+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:43:52.487+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:52.492+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:43:52.491+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:43:52.492+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:43:52.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.034 seconds
[2023-07-22T23:44:22.945+0000] {processor.py:157} INFO - Started process (PID=99151) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:22.949+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:44:22.951+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:22.951+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:22.961+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:22.959+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:44:22.962+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:23.009+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.073 seconds
[2023-07-22T23:44:53.180+0000] {processor.py:157} INFO - Started process (PID=99214) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:53.183+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:44:53.185+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:53.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:53.202+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:53.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 1
    from datetime import timedelta
    ^
IndentationError: unexpected indent
[2023-07-22T23:44:53.203+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:53.247+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.075 seconds
[2023-07-22T23:44:56.720+0000] {processor.py:157} INFO - Started process (PID=99225) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:56.721+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:44:56.723+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:56.723+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:56.732+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:44:56.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:44:56.733+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:44:56.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.043 seconds
[2023-07-22T23:45:26.793+0000] {processor.py:157} INFO - Started process (PID=99287) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:26.796+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:45:26.797+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:45:26.797+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:26.803+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:45:26.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:45:26.803+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:26.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.036 seconds
[2023-07-22T23:45:57.031+0000] {processor.py:157} INFO - Started process (PID=99345) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:57.037+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:45:57.039+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:45:57.038+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:57.049+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:45:57.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:45:57.050+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:45:57.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.054 seconds
[2023-07-22T23:46:27.900+0000] {processor.py:157} INFO - Started process (PID=99408) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:27.903+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:46:27.905+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:46:27.904+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:27.913+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:46:27.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:46:27.914+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:27.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.052 seconds
[2023-07-22T23:46:58.561+0000] {processor.py:157} INFO - Started process (PID=99471) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:58.563+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:46:58.566+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:46:58.565+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:58.582+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:46:58.577+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:46:58.584+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:46:58.615+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.061 seconds
[2023-07-22T23:47:29.488+0000] {processor.py:157} INFO - Started process (PID=99534) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:29.492+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:47:29.495+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:47:29.494+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:29.502+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:47:29.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:47:29.503+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:29.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.093 seconds
[2023-07-22T23:47:59.920+0000] {processor.py:157} INFO - Started process (PID=99604) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:59.922+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:47:59.924+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:47:59.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:59.931+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:47:59.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:47:59.932+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:47:59.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.049 seconds
[2023-07-22T23:48:30.246+0000] {processor.py:157} INFO - Started process (PID=99667) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:48:30.249+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:48:30.251+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:48:30.250+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:48:30.258+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:48:30.256+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:48:30.258+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:48:30.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.050 seconds
[2023-07-22T23:49:00.551+0000] {processor.py:157} INFO - Started process (PID=99730) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:00.554+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:49:00.555+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:49:00.555+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:00.564+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:49:00.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 12
    catchup=False
          ^
SyntaxError: invalid syntax
[2023-07-22T23:49:00.565+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:00.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.159 seconds
[2023-07-22T23:49:29.939+0000] {processor.py:157} INFO - Started process (PID=99784) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:29.945+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:49:29.950+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:49:29.949+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:29.963+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:49:29.961+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:49:29.964+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:49:29.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.057 seconds
[2023-07-22T23:50:00.219+0000] {processor.py:157} INFO - Started process (PID=99847) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:00.222+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:50:00.225+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:50:00.224+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:00.234+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:50:00.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:50:00.235+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:00.261+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.050 seconds
[2023-07-22T23:50:30.630+0000] {processor.py:157} INFO - Started process (PID=99917) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:30.633+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:50:30.636+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:50:30.635+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:30.651+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:50:30.649+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:50:30.653+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:50:30.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.071 seconds
[2023-07-22T23:51:01.028+0000] {processor.py:157} INFO - Started process (PID=99980) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:01.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:51:01.031+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:51:01.030+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:01.036+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:51:01.035+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:51:01.037+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:01.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.036 seconds
[2023-07-22T23:51:31.721+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:31.724+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:51:31.725+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:51:31.725+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:31.732+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:51:31.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:51:31.732+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:51:31.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.069 seconds
[2023-07-22T23:52:01.907+0000] {processor.py:157} INFO - Started process (PID=408) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:01.909+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:52:01.911+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:52:01.910+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:01.918+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:52:01.917+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:52:01.919+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:01.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.056 seconds
[2023-07-22T23:52:32.594+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:32.596+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:52:32.598+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:52:32.598+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:32.606+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:52:32.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:52:32.608+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:52:32.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.046 seconds
[2023-07-22T23:53:03.059+0000] {processor.py:157} INFO - Started process (PID=534) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:03.061+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:53:03.063+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:53:03.062+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:03.070+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:53:03.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:53:03.071+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:03.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.057 seconds
[2023-07-22T23:53:33.881+0000] {processor.py:157} INFO - Started process (PID=597) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:33.883+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:53:33.884+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:53:33.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:33.890+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:53:33.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:53:33.891+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:53:33.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.036 seconds
[2023-07-22T23:54:04.571+0000] {processor.py:157} INFO - Started process (PID=660) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:04.577+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:54:04.579+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:54:04.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:04.621+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:54:04.617+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:54:04.628+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:04.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.104 seconds
[2023-07-22T23:54:35.065+0000] {processor.py:157} INFO - Started process (PID=723) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:35.067+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:54:35.069+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:54:35.069+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:35.080+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:54:35.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:54:35.081+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:54:35.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.044 seconds
[2023-07-22T23:55:05.537+0000] {processor.py:157} INFO - Started process (PID=792) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:05.539+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:55:05.541+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:55:05.541+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:05.548+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:55:05.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:55:05.549+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:05.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.041 seconds
[2023-07-22T23:55:36.120+0000] {processor.py:157} INFO - Started process (PID=860) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:36.123+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:55:36.125+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:55:36.125+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:36.133+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:55:36.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:55:36.134+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:55:36.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.048 seconds
[2023-07-22T23:56:06.618+0000] {processor.py:157} INFO - Started process (PID=923) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:06.620+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:56:06.622+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:56:06.622+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:06.629+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:56:06.627+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:56:06.630+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:06.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.048 seconds
[2023-07-22T23:56:37.005+0000] {processor.py:157} INFO - Started process (PID=986) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:37.008+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:56:37.009+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:56:37.008+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:37.028+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:56:37.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:56:37.029+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:56:37.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.086 seconds
[2023-07-22T23:57:07.739+0000] {processor.py:157} INFO - Started process (PID=1049) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:07.741+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:57:07.742+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:57:07.742+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:07.748+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:57:07.746+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:57:07.748+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:07.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.036 seconds
[2023-07-22T23:57:38.158+0000] {processor.py:157} INFO - Started process (PID=1112) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:38.161+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:57:38.163+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:57:38.162+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:38.170+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:57:38.169+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:57:38.171+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:57:38.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.041 seconds
[2023-07-22T23:58:08.265+0000] {processor.py:157} INFO - Started process (PID=1175) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:08.267+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:58:08.268+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:58:08.268+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:08.273+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:58:08.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:58:08.276+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:08.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.036 seconds
[2023-07-22T23:58:30.501+0000] {processor.py:157} INFO - Started process (PID=1213) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:30.502+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:58:30.503+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:58:30.502+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:30.507+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:58:30.506+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:58:30.507+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:58:30.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.025 seconds
[2023-07-22T23:59:00.609+0000] {processor.py:157} INFO - Started process (PID=1271) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:00.612+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:59:00.615+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:00.614+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:00.627+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:00.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:59:00.631+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:00.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.077 seconds
[2023-07-22T23:59:05.599+0000] {processor.py:157} INFO - Started process (PID=1293) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:05.601+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:59:05.603+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:05.603+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:05.610+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:05.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:59:05.611+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:05.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.061 seconds
[2023-07-22T23:59:36.613+0000] {processor.py:157} INFO - Started process (PID=1358) to work on /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:36.615+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/postgres_db_dag.py for tasks to queue
[2023-07-22T23:59:36.617+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:36.616+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:36.625+0000] {logging_mixin.py:150} INFO - [2023-07-22T23:59:36.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/postgres_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_db_dag.py", line 7
    get_movie_data():
                    ^
SyntaxError: invalid syntax
[2023-07-22T23:59:36.626+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_db_dag.py
[2023-07-22T23:59:36.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/postgres_db_dag.py took 0.051 seconds
