[2023-07-21T13:22:01.365+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.send_email scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-07-21T13:22:01.390+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.send_email scheduled__2023-07-18T00:00:00+00:00 [queued]>
[2023-07-21T13:22:01.391+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-21T13:22:01.406+0000] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-07-18 00:00:00+00:00
[2023-07-21T13:22:01.414+0000] {standard_task_runner.py:57} INFO - Started process 93 to run task
[2023-07-21T13:22:01.421+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'send_email', 'scheduled__2023-07-18T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5hd9jpck']
[2023-07-21T13:22:01.424+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask send_email
[2023-07-21T13:22:01.488+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag.send_email scheduled__2023-07-18T00:00:00+00:00 [running]> on host ab92f9d9cc0f
[2023-07-21T13:22:01.582+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lovepreet.multani20@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-18T00:00:00+00:00'
[2023-07-21T13:22:01.609+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:153: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-07-21T13:22:01.622+0000] {configuration.py:673} WARNING - section/key [smtp/smtp_user] not found in config
[2023-07-21T13:22:01.644+0000] {email.py:269} INFO - Email alerting: attempt 1
[2023-07-21T13:22:01.659+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 92, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 153, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 271, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-07-21T13:22:01.681+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=first_dag, task_id=send_email, execution_date=20230718T000000, start_date=20230721T132201, end_date=20230721T132201
[2023-07-21T13:22:01.682+0000] {logging_mixin.py:150} INFO - Fail works  !  
[2023-07-21T13:22:01.691+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 68 for task send_email ([Errno 99] Cannot assign requested address; 93)
[2023-07-21T13:22:01.723+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T13:22:01.756+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
